<a href="https://colab.research.google.com/github/Harshithpalan/NUMY-NUMERICAL-PYTHON/blob/main/DL_d_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMY-NUMERICAL PYTHON

In [ ]:
#Import Numpy
import numpy as np

list = [1,2,3,4]
arr = np.array([1,2,3,4])

print(list*2) #repeate the same list
print(arr*2) #multplies each element
#numpy is faaster + smarter + math-ready


[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [ ]:
#multi-dimentional arrays
#single dimention
arr = np.array([10, 20, 30, 40, 50])
print(arr)
#two dimentional array---rows x columns
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr2)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


In [ ]:
#pre-filled array
z = np.zeros(5)
o = np.ones(5)
print(z)
print(o)
r = np.arange(1,11)
print(r)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#How to generate a random number
nums = np.random.rand(5)
print(nums)

[0.72961494 0.92523778 0.36702163 0.84223061 0.42791767]


In [ ]:
#array properties
a = np.array([[1,2,3],[4,5,6]]) #2d array
print(a.shape) #rows and column
print(a.size) #total number of elements
print(a.ndim) #to check the dimentionality

(2, 3)
6
2


In [ ]:
#indexing and slicing in arrays
a = np.array([10, 20, 30, 40])
print(a[-2]) #indexing
print(a[1:4]) #slicing

#2D indexing
b = np.array([[1, 2, 4],
              [5, 6, 7]])
print(b[0,1])
print(b[1,2])

30
[20 30 40]
2
7


In [ ]:
#Mathematical operations on array
#element wise match
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [ ]:
#Statistical function
a = np.array([10, 20, 30, 40, 50])

print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

30.0
50
10
14.142135623730951


In [ ]:
#universal function
a = np.array([1,4,9])

print(np.sqrt(a))
print(np.log(a))
print(a + 10) #added each element without using loop

[1. 2. 3.]
[0.         1.38629436 2.19722458]
[11 14 19]


In [ ]:
#reshaping in array
a = np.arange(1,13)
print(a)
#reshape changes 1D into 2D
b = a.reshape(3, 4)
print(b)
#flatten changes back 2D into 1D
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Matrix operations // simulation how neurons calculate output
a = np.array([[1,2,],
             [3,4]])
b = np.array ([[5,6],
              [7,8]])

print(np.dot(a,b))
#transpose
print(a.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
#boolean Masking(Filtering)
a = np.array([10, 20, 30, 40, 50])

print(a[a >= 20])

[20 30 40 50]


In [ ]:
#saving and loading
np.save("data.npy",a)
b = np.load("data.npy")
print(b)

[10 20 30 40 50]
